### python常用内置函数

In [11]:
### print(): 打印输出
print('abc')
print('-----')
### range(): 创建一个整数列表，一般用于for循环
for i in range(4):
  print(i)
### enumerate(): 将一个可遍历的数据对象(如列表)组合为一个索引序列，同时列出数据和数据序号，一般用在for循环当中。
print('-----')
nums = ['a', 'b', 'c']
for i, num in enumerate(nums):
  print(i, num)
print('-----')


abc
-----
0
1
2
3
-----
0 a
1 b
2 c
-----


In [22]:
### abs(): 取绝对值
print(abs(-2.3))
print('-----')
### round(): 四舍五入
print(round(3.5))
print('-----')
### sum():求和, 参数为可迭代对象，如list
print(sum([4,3]))
print('-----')
### len():求长度，参数为可迭代对象，如list
print(len([1,2,3]))
print('-----')
### sorted():排序，参数为可迭代对象
print(sorted([3,2,5]))


2.3
-----
4
-----
7
-----
3
-----
[2, 3, 5]


### Python库调用：numpy、pandas、matplotlib

numpy

In [2]:
import numpy as np ## 导入

numpy对象属性: 维数（ndim)，形状（shape），元素个数（size）

In [14]:

a = np.array([[1,2,3],[3,4,5]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(2, 3)
6


创建数组

In [15]:
a = np.array([1,2,3], dtype=np.int32)  #指定类型
a = np.array([1,2,3], dtype=np.float32)  #指定类型
a.dtype


dtype('float32')

In [33]:
## 创建特定数据
a = np.zeros(shape=(3,4))  ## 创建全是0数组
a = np.ones(shape=(3,4), dtype=np.int32)  ## 创建全是0数组
a = np.arange(10,20,2)  ## 创建连续数组
a = np.linspace(1,10,20)  ## 创建连续数组
print(a)


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


基本运算-1

In [50]:
## 基本运算(一维)
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
c = a+b
c = a-b
c = a*b
c = a**b
print(c)


[   1    8   81 1024]


In [54]:
## 简单统计:平均值、最大值、最小值、求和、标准差。
d = np.mean(c)
d = np.max(c)
d = np.min(c)
d = np.sum(c)
d = np.std(c)
print(d)

431.5532991416008


In [58]:
## 基本运算(二维)
a = np.array([[1,2],
              [2,3]])
b = np.array([[3,4],
              [4,5]])
c = a*b
c = np.dot(a,b)
print(c)



[[11 14]
 [18 23]]


In [59]:
## 简单统计(二维):平均值、最大值、最小值、求和、标准差。
d = np.mean(c)
d = np.mean(c, axis=0)  ## 行维度上取平均
print(d)



[14.5 18.5]


索引

In [5]:
a = np.arange(1,10).reshape(3,3)
print(a)
a[0, 1]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

合并

In [20]:
## 一维
a = np.array([1,2,3])
print(a)
b = np.array([4,5,6])
c = np.hstack((a,b))
c = np.vstack((a,b))


[1 2 3]


In [26]:
a = np.array([1,2,3]).reshape(1,3)
print(a)
b = np.array([4,5,6]).reshape(1,3)
c = np.concatenate((a,b), axis=1)
print(c)


[[1 2 3]]
[[1 2 3 4 5 6]]


浅复制与深复制

In [30]:
### 浅复制
a = np.array([1,2,3])
b = a    ## 内存地址的复制，不是值的复制。
print(a, b)
a[0] = 11
print(a, b)
b[0] = 22
print(a, b)



[1 2 3] [1 2 3]
[11  2  3] [11  2  3]
[22  2  3] [22  2  3]


In [33]:
### 深复制
a = np.array([1,2,3])
b = a.copy()    ## 复制a地址所指向的数据，b变量指向的是新复制数据的新地址。
print(a, b)
a[0] = 11
print(a, b)
b[0] = 22
print(a, b)


[1 2 3] [1 2 3]
[11  2  3] [1 2 3]
[11  2  3] [22  2  3]
